/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.cpu;

public final class R {
    public static final class array {
        public static final int test_arr=0x7f060000;
    }
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f080000;
        public static final int activity_vertical_margin=0x7f080001;
    }
    public static final class drawable {
        public static final int audio_imgpause=0x7f020000;
        public static final int audio_imgplay=0x7f020001;
        public static final int btn=0x7f020002;
        public static final int btn_active=0x7f020003;
        public static final int btn_disactive=0x7f020004;
        public static final int catatan=0x7f020005;
        public static final int compas=0x7f020006;
        public static final int directory_icon=0x7f020007;
        public static final int directory_up=0x7f020008;
        public static final int favicon=0x7f020009;
        public static final int file=0x7f02000a;
        public static final int file_icon=0x7f02000b;
        public static final int folder=0x7f02000c;
        public static final int folder_in=0x7f02000d;
        public static final int ic_launcher=0x7f02000e;
        public static final int ic_menu_cookies=0x7f02000f;
        public static final int ic_menu_html=0x7f020010;
        public static final int icon=0x7f020011;
        public static final int icon_apk=0x7f020012;
        public static final int icon_config=0x7f020013;
        public static final int icon_css=0x7f020014;
        public static final int icon_db=0x7f020015;
        public static final int icon_doc=0x7f020016;
        public static final int icon_gen=0x7f020017;
        public static final int icon_html=0x7f020018;
        public static final int icon_image=0x7f020019;
        public static final int icon_music=0x7f02001a;
        public static final int icon_pdf=0x7f02001b;
        public static final int icon_php=0x7f02001c;
        public static final int icon_ppt=0x7f02001d;
        public static final int icon_txt=0x7f02001e;
        public static final int icon_video=0x7f02001f;
        public static final int icon_zip=0x7f020020;
        public static final int iris=0x7f020021;
        public static final int mouse_pointer=0x7f020022;
        public static final int red_mark=0x7f020023;
        public static final int setting=0x7f020024;
        public static final int trans=0x7f020025;
        public static final int transm=0x7f020026;
    }
    public static final class id {
        public static final int TextView01=0x7f0b0048;
        public static final int TextView02=0x7f0b0049;
        public static final int TextViewDate=0x7f0b004a;
        public static final int aButton=0x7f0b0011;
        public static final int aEdit=0x7f0b0010;
        public static final int about=0x7f0b007f;
        public static final int alat=0x7f0b0076;
        public static final int alert_btnnf=0x7f0b0009;
        public static final int alert_cariOke=0x7f0b0001;
        public static final int alert_edCari=0x7f0b0000;
        public static final int alert_file_find_r=0x7f0b0005;
        public static final int alert_list=0x7f0b0002;
        public static final int alert_maju=0x7f0b0004;
        public static final int alert_mundur=0x7f0b0003;
        public static final int alert_nfed=0x7f0b0008;
        public static final int alert_paket_button=0x7f0b000c;
        public static final int alert_paket_nama=0x7f0b000a;
        public static final int alert_paket_url=0x7f0b000b;
        public static final int amButton=0x7f0b0007;
        public static final int amEdit=0x7f0b0006;
        public static final int apk_button=0x7f0b002a;
        public static final int apk_imageView=0x7f0b001d;
        public static final int apk_listview=0x7f0b002b;
        public static final int apk_txtName=0x7f0b001e;
        public static final int apk_txtPackage=0x7f0b0020;
        public static final int apk_txtPaket=0x7f0b001f;
        public static final int apk_user_appIcon=0x7f0b0021;
        public static final int apk_user_listView=0x7f0b002c;
        public static final int apk_user_textViewNameItem=0x7f0b0022;
        public static final int apk_user_textViewPackageItem=0x7f0b0024;
        public static final int apk_user_textViewSize=0x7f0b0023;
        public static final int audio_line1=0x7f0b0031;
        public static final int audio_line2=0x7f0b0032;
        public static final int audio_loading=0x7f0b002e;
        public static final int audio_playpause=0x7f0b0033;
        public static final int audio_progress=0x7f0b002f;
        public static final int audio_spinner=0x7f0b002d;
        public static final int audio_titleandbuttons=0x7f0b0030;
        public static final int btnLog_server=0x7f0b0068;
        public static final int btnLog_server_mysql=0x7f0b0067;
        public static final int btnLog_server_php=0x7f0b0066;
        public static final int btn_Pdir=0x7f0b0055;
        public static final int btn_Pmulut=0x7f0b0054;
        public static final int btn_Ptelinga=0x7f0b0053;
        public static final int btn_editor_color=0x7f0b0058;
        public static final int btn_local=0x7f0b0056;
        public static final int btn_okeC=0x7f0b005e;
        public static final int btn_panel=0x7f0b0040;
        public static final int btn_server_root_dir=0x7f0b0061;
        public static final int btn_server_run_phpmyadmin=0x7f0b0065;
        public static final int btn_server_site_editor=0x7f0b0063;
        public static final int btn_server_start=0x7f0b005f;
        public static final int clear=0x7f0b007e;
        public static final int console=0x7f0b003c;
        public static final int disp=0x7f0b006a;
        public static final int dom=0x7f0b003a;
        public static final int editText_docFolder=0x7f0b0016;
        public static final int editor_btnMenu=0x7f0b0044;
        public static final int editor_btnNext=0x7f0b0042;
        public static final int editor_btnPrev=0x7f0b0041;
        public static final int editor_btnSave=0x7f0b0043;
        public static final int editor_editCode=0x7f0b0046;
        public static final int edt_negaraC=0x7f0b005d;
        public static final int edt_tempatC=0x7f0b005c;
        public static final int favicon=0x7f0b0037;
        public static final int fd_Icon1=0x7f0b0047;
        public static final int fd_activity_surface_view=0x7f0b004e;
        public static final int file_edt=0x7f0b004d;
        public static final int file_list=0x7f0b004c;
        public static final int full_path=0x7f0b004b;
        public static final int goto_url=0x7f0b0034;
        public static final int graph=0x7f0b006b;
        public static final int history=0x7f0b0026;
        public static final int historyBack=0x7f0b0014;
        public static final int historyList=0x7f0b0015;
        public static final int html_title=0x7f0b0038;
        public static final int image=0x7f0b0073;
        public static final int imageView=0x7f0b0012;
        public static final int imageViewCompass=0x7f0b003f;
        public static final int info_server_root_dir=0x7f0b0062;
        public static final int keyb_batal=0x7f0b0018;
        public static final int keyb_message=0x7f0b0017;
        public static final int label_author=0x7f0b0069;
        public static final int layout=0x7f0b0072;
        public static final int list_catatan=0x7f0b003d;
        public static final int list_header=0x7f0b001b;
        public static final int list_image=0x7f0b001a;
        public static final int list_item=0x7f0b0013;
        public static final int list_subheader=0x7f0b001c;
        public static final int main=0x7f0b0077;
        public static final int main_edit=0x7f0b0025;
        public static final int main_text=0x7f0b0029;
        public static final int memori_list=0x7f0b0050;
        public static final int memori_status=0x7f0b004f;
        public static final int okresponse=0x7f0b007a;
        public static final int otherresponse=0x7f0b007b;
        public static final int paket_list=0x7f0b0052;
        public static final int paket_status=0x7f0b0051;
        public static final int pengaturan_catatan=0x7f0b005a;
        public static final int pengaturan_notif_fb=0x7f0b005b;
        public static final int pengaturan_service=0x7f0b0057;
        public static final int pengaturan_touch=0x7f0b0059;
        public static final int progressBar_url_loading=0x7f0b0039;
        public static final int rg=0x7f0b000d;
        public static final int rg1=0x7f0b000e;
        public static final int rg2=0x7f0b000f;
        public static final int riwayat=0x7f0b007c;
        public static final int server_help=0x7f0b0064;
        public static final int server_info=0x7f0b0060;
        public static final int startspeak=0x7f0b0027;
        public static final int starttask=0x7f0b003b;
        public static final int statusBack=0x7f0b0079;
        public static final int terminal_input=0x7f0b006c;
        public static final int terminal_output=0x7f0b006e;
        public static final int terminal_submit=0x7f0b006d;
        public static final int text=0x7f0b0075;
        public static final int text1=0x7f0b0078;
        public static final int thumbnail=0x7f0b0019;
        public static final int title=0x7f0b0074;
        public static final int toast=0x7f0b007d;
        public static final int touch_app=0x7f0b0071;
        public static final int touch_home=0x7f0b006f;
        public static final int touch_recent=0x7f0b0070;
        public static final int tscroll=0x7f0b0028;
        public static final int tvHeading=0x7f0b003e;
        public static final int verticalNumsLine=0x7f0b0045;
        public static final int webTitlePanel=0x7f0b0036;
        public static final int web_view=0x7f0b0035;
    }
    public static final class layout {
        public static final int alert_file=0x7f030000;
        public static final int alert_file_find_result=0x7f030001;
        public static final int alert_memori=0x7f030002;
        public static final int alert_newfile=0x7f030003;
        public static final int alert_paket=0x7f030004;
        public static final int alert_telinga=0x7f030005;
        public static final int cursor=0x7f030006;
        public static final int file_find=0x7f030007;
        public static final int history_subdomner=0x7f030008;
        public static final int input_field=0x7f030009;
        public static final int keyboardwifi=0x7f03000a;
        public static final int list_row=0x7f03000b;
        public static final int list_row_apk=0x7f03000c;
        public static final int list_row_apk_user=0x7f03000d;
        public static final int main=0x7f03000e;
        public static final int main_apk=0x7f03000f;
        public static final int main_apk_user=0x7f030010;
        public static final int main_audio=0x7f030011;
        public static final int main_browser=0x7f030012;
        public static final int main_browser_subdomner=0x7f030013;
        public static final int main_catatan=0x7f030014;
        public static final int main_compas=0x7f030015;
        public static final int main_editor=0x7f030016;
        public static final int main_fileexploler=0x7f030017;
        public static final int main_filemanager=0x7f030018;
        public static final int main_mata=0x7f030019;
        public static final int main_memori=0x7f03001a;
        public static final int main_paket=0x7f03001b;
        public static final int main_pengaturan=0x7f03001c;
        public static final int main_server=0x7f03001d;
        public static final int main_status=0x7f03001e;
        public static final int main_status_tasklist=0x7f03001f;
        public static final int main_terminal=0x7f030020;
        public static final int main_touch=0x7f030021;
        public static final int notifi=0x7f030022;
        public static final int service_layout=0x7f030023;
        public static final int spinner_item=0x7f030024;
        public static final int status_subdomner=0x7f030025;
        public static final int toast=0x7f030026;
    }
    public static final class menu {
        public static final int menu=0x7f0a0000;
    }
    public static final class raw {
        public static final int lbpcascade_frontalface=0x7f050000;
        public static final int mouse_udp_client=0x7f050001;
    }
    public static final class string {
        public static final int app_name=0x7f090000;
        public static final int disp_battery=0x7f090006;
        public static final int disp_cell=0x7f090003;
        public static final int disp_cpu=0x7f090004;
        public static final int disp_cpu_type=0x7f090005;
        public static final int disp_in=0x7f090009;
        public static final int disp_name=0x7f090007;
        public static final int disp_out=0x7f09000a;
        public static final int disp_system=0x7f09000c;
        public static final int disp_type=0x7f090008;
        public static final int disp_user=0x7f09000b;
        public static final int disp_wifi=0x7f090002;
        public static final int exists_processes=0x7f090010;
        public static final int hello_world=0x7f090001;
        public static final int help_server=0x7f090012;
        public static final int input_other_path=0x7f09000f;
        public static final int progress_dialog_message=0x7f090011;
        public static final int view_cookies=0x7f09000e;
        public static final int view_html=0x7f09000d;
    }
    public static final class style {
        public static final int AppTheme=0x7f070001;
        public static final int BtnStyle=0x7f070000;
    }
    public static final class xml {
        public static final int btn_nowplaying_background_small=0x7f040000;
        public static final int fon_title=0x7f040001;
        public static final int gradient_bg_1=0x7f040002;
        public static final int gradient_bg_2=0x7f040003;
        public static final int keybwifi=0x7f040004;
        public static final int list_selector=0x7f040005;
        public static final int mouse=0x7f040006;
        public static final int my_btn=0x7f040007;
        public static final int my_state_colors=0x7f040008;
        public static final int progress_horizontal=0x7f040009;
        public static final int seek_thumb=0x7f04000a;
        public static final int tab_header=0x7f04000b;
    }
}
